import { z } from "zod"
import { ticker, dateStr, expiry, flowGroup, flowOutput, optionKind } from "../validation.js"
import type { ToolCatalog } from "../engine.js"

export const flowAnalysisCatalog: ToolCatalog = {
  id: "uw_flow",
  summary: `Access UnusualWhales options flow data including flow alerts, full tape, net flow, group flow, and lit exchange flow.

Available commands:
- flow_alerts: Get flow alerts with extensive filtering options
- flow_alert: Get a single flow alert by ID with all constituent trades (id required; older_than optional). For multi-leg alerts returns all related legs; for RepeatedHits returns all transactions.
- full_tape: Get full options tape for a date (date required)
- net_flow_expiry: Get net flow by expiry date (date optional)
- group_greek_flow: Get greek flow (delta & vega) for a flow group (flow_group required; date optional)
- group_greek_flow_expiry: Get greek flow by expiry for a flow group (flow_group, expiry required; date optional)
- lit_flow_recent: Get recent lit exchange trades across the market
- lit_flow_ticker: Get lit exchange trades for a specific ticker (ticker required)
- exchange_breakdown: Get exchange & trade-code breakdown for a date (date required; ticker, by_trade_code, min_premium, limit, page, order optional)
- optionable_tickers: Get the list of optionable tickers (ticker optional)
- option_trades: Filter the full option trades tape — same data and filters as the live options flow page (all params optional)
- multi_leg_trades: Get detected multi-leg strategies (verticals, condors, butterflies, calendars, diagonals) with net price, premium and greeks (all params optional)
- multi_leg_legs: Get the individual legs of one multi-leg strategy (id required)

Flow groups: airline, bank, basic materials, china, communication services, consumer cyclical, consumer defensive, crypto, cyber, energy, financial services, gas, gold, healthcare, industrials, mag7, oil, real estate, refiners, reit, semi, silver, technology, uranium, utilities

Flow alerts filtering options include: ticker, premium range, volume range, OI range, DTE range, and more.
Lit flow filtering options include: premium range, size range, volume range, and timestamp filters.`,
  outputSchema: flowOutput,
  commands: [
    {
      name: "flow_alerts",
      route: "/api/option-trades/flow-alerts",
      params: z.object({
        ticker_symbol: z.string().describe("Comma-separated list of ticker symbols to filter by. Prefix with '-' to exclude tickers (e.g., 'AAPL,INTC' or '-TSLA,NVDA')").optional(),
        limit: z.number().int().min(1).max(500).describe("Maximum number of results").default(100).optional(),
        min_premium: z.number().int().nonnegative().default(0).describe("The minimum premium on the alert or trade").optional(),
        max_premium: z.number().int().nonnegative().describe("The maximum premium on the alert or trade").optional(),
        min_size: z.number().int().nonnegative().default(0).describe("The minimum size on that alert").optional(),
        max_size: z.number().int().nonnegative().describe("The maximum size on that alert").optional(),
        min_dte: z.number().int().min(0).describe("The minimum days to expiry").optional(),
        max_dte: z.number().int().min(0).describe("The maximum days to expiry").optional(),
        is_floor: z.boolean().default(true).describe("Whether a transaction is from the floor").optional(),
        is_sweep: z.boolean().default(true).describe("Whether a transaction is an intermarket sweep").optional(),
        is_multi_leg: z.boolean().describe("Whether the transaction is multi-leg").optional(),
        min_volume: z.number().int().nonnegative().describe("Minimum volume on the contract").optional(),
        max_volume: z.number().int().nonnegative().describe("Maximum volume on the contract").optional(),
        min_open_interest: z.number().int().nonnegative().describe("Minimum open interest").optional(),
        max_open_interest: z.number().int().nonnegative().describe("Maximum open interest").optional(),
        all_opening: z.boolean().default(true).describe("Whether all transactions are opening").optional(),
        is_call: z.boolean().default(true).describe("Whether a transaction is a call").optional(),
        is_put: z.boolean().default(true).describe("Whether a transaction is a put").optional(),
        is_ask_side: z.boolean().default(true).describe("Whether a transaction is ask side").optional(),
        is_bid_side: z.boolean().default(true).describe("Whether a transaction is bid side").optional(),
        is_otm: z.boolean().describe("Only include OTM contracts").optional(),
        size_greater_oi: z.boolean().describe("Size greater than open interest").optional(),
        vol_greater_oi: z.boolean().describe("Volume greater than open interest").optional(),
        rule_name: z.array(z.string()).describe("Filter by alert rule names").optional(),
        issue_types: z.array(z.string()).describe("Filter by issue types").optional(),
        min_diff: z.number().describe("Minimum OTM diff").optional(),
        max_diff: z.number().describe("Maximum OTM diff").optional(),
        min_volume_oi_ratio: z.number().int().min(0).describe("Minimum volume/OI ratio").optional(),
        max_volume_oi_ratio: z.number().int().min(0).describe("Maximum volume/OI ratio").optional(),
        min_ask_perc: z.number().min(0).max(1).describe("Minimum ask percentage (0-1)").optional(),
        max_ask_perc: z.number().min(0).max(1).describe("Maximum ask percentage (0-1)").optional(),
        min_bid_perc: z.number().min(0).max(1).describe("Minimum bid percentage (0-1)").optional(),
        max_bid_perc: z.number().min(0).max(1).describe("Maximum bid percentage (0-1)").optional(),
        min_bull_perc: z.number().min(0).max(1).describe("Minimum bull percentage (0-1)").optional(),
        max_bull_perc: z.number().min(0).max(1).describe("Maximum bull percentage (0-1)").optional(),
        min_bear_perc: z.number().min(0).max(1).describe("Minimum bear percentage (0-1)").optional(),
        max_bear_perc: z.number().min(0).max(1).describe("Maximum bear percentage (0-1)").optional(),
        min_skew: z.number().min(0).max(1).describe("Minimum skew (0-1)").optional(),
        max_skew: z.number().min(0).max(1).describe("Maximum skew (0-1)").optional(),
        min_price: z.number().min(0).describe("Minimum underlying price").optional(),
        max_price: z.number().min(0).describe("Maximum underlying price").optional(),
        min_iv_change: z.number().min(0).describe("Minimum IV change").optional(),
        max_iv_change: z.number().min(0).describe("Maximum IV change").optional(),
        min_size_vol_ratio: z.number().min(0).max(1).describe("Minimum size/volume ratio").optional(),
        max_size_vol_ratio: z.number().min(0).max(1).describe("Maximum size/volume ratio").optional(),
        min_spread: z.number().min(0).describe("Minimum spread").optional(),
        max_spread: z.number().min(0).max(1).describe("Maximum spread").optional(),
        min_marketcap: z.number().nonnegative().describe("Minimum market cap in USD").optional(),
        max_marketcap: z.number().nonnegative().describe("Maximum market cap in USD").optional(),
        newer_than: z.string().describe("Filter alerts newer than UTC timestamp").optional(),
        older_than: z.string().describe("Filter alerts older than UTC timestamp").optional(),
        min_days_between_expiry_and_earnings: z.number().int().describe("Minimum days between expiry and earnings").optional(),
        max_days_between_expiry_and_earnings: z.number().int().describe("Maximum days between expiry and earnings").optional(),
        unusual: z.boolean().describe("Convenience preset matching the live 'unusual' flow filter").optional(),
      }),
      queryRenames: { rule_name: "rule_name[]", issue_types: "issue_types[]" },
    },
    { name: "flow_alert", route: "/api/option-trades/flow-alerts/{id}", params: z.object({ id: z.string().uuid().describe("UUID of the flow alert"), older_than: z.string().describe("Return trades older than this UTC timestamp").optional() }) },
    { name: "full_tape", route: "/api/option-trades/full-tape/{date}", premium: true, params: z.object({ date: dateStr.describe("Date in YYYY-MM-DD format (required)") }) },
    { name: "net_flow_expiry", route: "/api/net-flow/expiry", params: z.object({ date: dateStr.optional(), moneyness: z.string().describe("Filter by moneyness (all, itm, otm, atm)").optional(), tide_type: z.string().describe("Filter by tide type (all, equity_only, etf_only, index_only)").optional(), expiration: z.string().describe("Filter by expiration type (weekly, zero_dte)").optional() }) },
    { name: "group_greek_flow", route: "/api/group-flow/{flow_group}/greek-flow", params: z.object({ flow_group: flowGroup, date: dateStr.optional() }) },
    { name: "group_greek_flow_expiry", route: "/api/group-flow/{flow_group}/greek-flow/{expiry}", params: z.object({ flow_group: flowGroup, expiry, date: dateStr.optional() }) },
    {
      name: "lit_flow_recent",
      route: "/api/lit-flow/recent",
      params: z.object({
        date: dateStr.optional(),
        limit: z.number().int().min(1).max(500).default(100).optional(),
        min_premium: z.number().int().nonnegative().default(0).describe("Minimum premium").optional(),
        max_premium: z.number().int().nonnegative().describe("Maximum premium").optional(),
        min_size: z.number().int().nonnegative().default(0).describe("Minimum size").optional(),
        max_size: z.number().int().nonnegative().describe("Maximum size").optional(),
        min_volume: z.number().int().nonnegative().default(0).describe("Minimum volume").optional(),
        max_volume: z.number().int().nonnegative().describe("Maximum volume").optional(),
      }),
    },
    {
      name: "lit_flow_ticker",
      route: "/api/lit-flow/{ticker}",
      params: z.object({
        ticker: ticker.describe("Ticker symbol (required)"),
        date: dateStr.optional(),
        limit: z.number().int().min(1).max(500).default(500).optional(),
        newer_than: z.string().describe("Filter trades newer than timestamp").optional(),
        older_than: z.string().describe("Filter trades older than timestamp").optional(),
        min_premium: z.number().int().nonnegative().default(0).describe("Minimum premium").optional(),
        max_premium: z.number().int().nonnegative().describe("Maximum premium").optional(),
        min_size: z.number().int().nonnegative().default(0).describe("Minimum size").optional(),
        max_size: z.number().int().nonnegative().describe("Maximum size").optional(),
        min_volume: z.number().int().nonnegative().default(0).describe("Minimum volume").optional(),
        max_volume: z.number().int().nonnegative().describe("Maximum volume").optional(),
      }),
    },
    { name: "exchange_breakdown", route: "/api/option-trades/exchange-breakdown/{date}", params: z.object({ date: dateStr.describe("Date in YYYY-MM-DD format (required)"), ticker: z.array(ticker).describe("Ticker symbols to filter by").optional(), by_trade_code: z.boolean().describe("Break down by trade code").optional(), min_premium: z.string().describe("Minimum premium").optional(), limit: z.number().int().min(1).max(500).describe("Maximum number of results").optional(), page: z.number().int().min(0).describe("Page number for paginated results").optional(), order: z.string().describe("Sort order").optional() }), queryRenames: { ticker: "ticker[]" } },
    { name: "optionable_tickers", route: "/api/option-trades/optionable-tickers", params: z.object({ ticker: ticker.optional() }) },
    {
      name: "option_trades",
      route: "/api/option-trades",
      params: z.object({
        limit: z.number().int().min(1).max(500).describe("Maximum number of results").optional(),
        ticker_symbol: z.string().describe("Comma-separated tickers. Prefix with '-' to exclude (e.g., 'AAPL,INTC' or '-TSLA')").optional(),
        option_contracts: z.array(z.string()).describe("Restrict to specific option contract symbols").optional(),
        chain: z.array(z.string()).describe("Restrict to specific option chains").optional(),
        strike: z.string().describe("Filter by strike price").optional(),
        type: optionKind.optional(),
        newer_than: z.string().describe("Only trades at/after this UTC timestamp (ISO-8601)").optional(),
        older_than: z.string().describe("Only trades at/before this UTC timestamp (ISO-8601)").optional(),
        canceled: z.boolean().describe("Include canceled trades").optional(),
        is_multi_leg: z.boolean().describe("Only multi-leg trades").optional(),
        volume_greater_oi: z.boolean().describe("Only trades where contract volume exceeds open interest").optional(),
        exclude_deep_itm: z.boolean().describe("Exclude deep in-the-money contracts").optional(),
        force_15_min_delay: z.boolean().describe("Force the 15-minute delayed tape").optional(),
        hide_expired: z.boolean().describe("Hide already-expired contracts").optional(),
        include_agg_trades: z.boolean().describe("Include aggregated trades").optional(),
        intraday_only: z.boolean().describe("Only trades from the current session").optional(),
        is_otm: z.boolean().describe("Only out-of-the-money contracts").optional(),
        opening: z.boolean().describe("Only opening transactions").optional(),
        opex_only: z.boolean().describe("Only monthly opex expirations").optional(),
        size_greater_oi: z.boolean().describe("Only trades where size exceeds open interest").optional(),
        exchanges: z.array(z.string()).describe("Filter by exchange codes").optional(),
        excluded_tags: z.array(z.string()).describe("Exclude trades carrying these tags").optional(),
        expiry_dates: z.array(z.string()).describe("Filter by expiry dates (YYYY-MM-DD)").optional(),
        industries: z.array(z.string()).describe("Filter by underlying industry").optional(),
        issue_types: z.array(z.string()).describe("Filter by issue type (e.g., 'Common Stock', 'ETF')").optional(),
        marketcap_size: z.array(z.string()).describe("Filter by market-cap bucket").optional(),
        report_flag: z.array(z.string()).describe("Filter by report flag").optional(),
        sectors: z.array(z.string()).describe("Filter by underlying sector").optional(),
        tags: z.array(z.string()).describe("Filter by trade tags").optional(),
        trade_codes: z.array(z.string()).describe("Filter by trade condition codes").optional(),
        min_ask_perc: z.number().describe("Minimum ask-side percentage").optional(),
        max_ask_perc: z.number().describe("Maximum ask-side percentage").optional(),
        min_bid_perc: z.number().describe("Minimum bid-side percentage").optional(),
        max_bid_perc: z.number().describe("Maximum bid-side percentage").optional(),
        min_bull_perc: z.number().describe("Minimum bullish percentage").optional(),
        max_bull_perc: z.number().describe("Maximum bullish percentage").optional(),
        min_bear_perc: z.number().describe("Minimum bearish percentage").optional(),
        max_bear_perc: z.number().describe("Maximum bearish percentage").optional(),
        min_skew: z.number().describe("Minimum skew").optional(),
        max_skew: z.number().describe("Maximum skew").optional(),
        min_days_between_expiry_and_earnings: z.number().int().describe("Minimum days between expiry and earnings").optional(),
        max_days_between_expiry_and_earnings: z.number().int().describe("Maximum days between expiry and earnings").optional(),
        min_dte: z.number().int().describe("Minimum days to expiry").optional(),
        max_dte: z.number().int().describe("Maximum days to expiry").optional(),
        min_earnings_dte: z.number().int().describe("Minimum days to the next earnings report").optional(),
        max_earnings_dte: z.number().int().describe("Maximum days to the next earnings report").optional(),
        min_open_interest: z.number().int().nonnegative().describe("Minimum open interest").optional(),
        max_open_interest: z.number().int().nonnegative().describe("Maximum open interest").optional(),
        min_volume: z.number().int().nonnegative().describe("Minimum contract volume").optional(),
        max_volume: z.number().int().nonnegative().describe("Maximum contract volume").optional(),
        min_size: z.number().int().nonnegative().describe("Minimum trade size").optional(),
        max_size: z.number().int().nonnegative().describe("Maximum trade size").optional(),
        min_delta: z.string().describe("Minimum delta").optional(),
        max_delta: z.string().describe("Maximum delta").optional(),
        min_gamma: z.string().describe("Minimum gamma").optional(),
        max_gamma: z.string().describe("Maximum gamma").optional(),
        min_iv: z.string().describe("Minimum implied volatility").optional(),
        max_iv: z.string().describe("Maximum implied volatility").optional(),
        min_theta: z.string().describe("Minimum theta").optional(),
        max_theta: z.string().describe("Maximum theta").optional(),
        min_diff: z.string().describe("Minimum OTM diff").optional(),
        max_diff: z.string().describe("Maximum OTM diff").optional(),
        min_marketcap: z.number().describe("Minimum underlying market cap in USD").optional(),
        max_marketcap: z.number().describe("Maximum underlying market cap in USD").optional(),
        min_strike: z.number().describe("Minimum strike price").optional(),
        max_strike: z.number().describe("Maximum strike price").optional(),
        min_vol_oi_ratio: z.number().describe("Minimum volume/open-interest ratio").optional(),
        max_vol_oi_ratio: z.number().describe("Maximum volume/open-interest ratio").optional(),
        min_premium: z.string().describe("Minimum premium (supports abs())").optional(),
        max_premium: z.string().describe("Maximum premium (supports abs())").optional(),
        min_price: z.string().describe("Minimum contract price").optional(),
        max_price: z.string().describe("Maximum contract price").optional(),
        min_spread: z.string().describe("Minimum bid/ask spread").optional(),
        max_spread: z.string().describe("Maximum bid/ask spread").optional(),
        min_underlying_price: z.string().describe("Minimum underlying price").optional(),
        max_underlying_price: z.string().describe("Maximum underlying price").optional(),
      }),
      queryRenames: {
        option_contracts: "option_contracts[]",
        chain: "chain[]",
        exchanges: "exchanges[]",
        excluded_tags: "excluded_tags[]",
        expiry_dates: "expiry_dates[]",
        industries: "industries[]",
        issue_types: "issue_types[]",
        marketcap_size: "marketcap_size[]",
        report_flag: "report_flag[]",
        sectors: "sectors[]",
        tags: "tags[]",
        trade_codes: "trade_codes[]",
      },
    },
    {
      name: "multi_leg_trades",
      route: "/api/option-trades/multi-leg",
      params: z.object({
        limit: z.number().int().min(1).max(500).describe("Rows per page (default 50, max 500)").optional(),
        offset: z.number().int().min(0).max(500).describe("Rows to skip for pagination (max 500)").optional(),
        ticker_symbol: z.string().describe("Restrict to a single underlying ticker").optional(),
        newer_than: z.string().describe("Only strategies executed at/after this UTC timestamp (ISO-8601)").optional(),
        older_than: z.string().describe("Only strategies executed at/before this UTC timestamp (ISO-8601)").optional(),
        strategy: z.array(z.string()).describe("Filter by detected strategy name(s), e.g. 'iron_condor', 'vertical'").optional(),
        exclude_other: z.boolean().describe("Exclude strategies classified as 'other' (unrecognized structures)").optional(),
        direction: z.array(z.enum(["long", "short"])).describe("Filter by direction").optional(),
        net_side: z.array(z.enum(["bid", "ask", "mid"])).describe("Filter by the strategy's net aggressor side").optional(),
        min_size: z.number().int().nonnegative().describe("Minimum total contracts across legs").optional(),
        max_size: z.number().int().nonnegative().describe("Maximum total contracts across legs").optional(),
        min_premium: z.string().describe("Minimum net premium (supports abs())").optional(),
        max_premium: z.string().describe("Maximum net premium (supports abs())").optional(),
        min_dte: z.number().int().describe("Minimum days to expiry").optional(),
        max_dte: z.number().int().describe("Maximum days to expiry").optional(),
        min_leg_count: z.number().int().min(1).describe("Minimum number of legs").optional(),
        max_leg_count: z.number().int().min(1).describe("Maximum number of legs").optional(),
        all_otm: z.boolean().describe("Only strategies where every leg is out-of-the-money").optional(),
        issue_types: z.array(z.string()).describe("Filter by underlying issue type(s), e.g. 'Common Stock', 'ETF'").optional(),
        sectors: z.array(z.string()).describe("Filter by underlying sector(s)").optional(),
      }),
      queryRenames: {
        strategy: "strategy[]",
        direction: "direction[]",
        net_side: "net_side[]",
        issue_types: "issue_types[]",
        sectors: "sectors[]",
      },
    },
    {
      name: "multi_leg_legs",
      route: "/api/option-trades/multi-leg/{id}/legs",
      params: z.object({
        id: z.string().describe("The multi-leg strategy id (UUID) from the multi_leg_trades feed"),
      }),
    },
  ],
}
