import { z } from "zod"
import { ticker, stockScreenerOrderBy, contractScreenerOrderBy } from "../validation.js"
import type { ToolCatalog } from "../engine.js"

export const screeningCatalog: ToolCatalog = {
  id: "uw_screener",
  summary: `Access UnusualWhales screeners for stocks, options, and analysts.

Available commands:
- stocks: Screen stocks with various filters
- option_contracts: Screen option contracts with filters
- analysts: Screen analyst ratings
- unusual_activity: Get option contracts flagged as unusual — the API equivalent of the live options flow "unusual" view (all params optional)`,
  commands: [
    {
      name: "stocks",
      route: "/api/screener/stocks",
      params: z.object({
        ticker: ticker.optional(),
        order: stockScreenerOrderBy.optional(),
        order_direction: z.enum(["asc", "desc"]).default("desc").optional(),
        min_marketcap: z.number().optional(),
        max_marketcap: z.number().optional(),
        min_volume: z.number().int().nonnegative().optional(),
        max_volume: z.number().int().nonnegative().optional(),
        min_oi: z.number().int().nonnegative().optional(),
        max_oi: z.number().int().nonnegative().optional(),
        min_premium: z.number().min(0).optional(),
        max_premium: z.number().min(0).optional(),
        issue_types: z.array(z.string()).optional(),
        sectors: z.array(z.string()).optional(),
        min_change: z.number().optional(),
        max_change: z.number().optional(),
        min_underlying_price: z.number().optional(),
        max_underlying_price: z.number().optional(),
        is_s_p_500: z.boolean().optional(),
        has_dividends: z.boolean().optional(),
        min_perc_3_day_total: z.number().optional(),
        max_perc_3_day_total: z.number().optional(),
        min_perc_3_day_call: z.number().optional(),
        max_perc_3_day_call: z.number().optional(),
        min_perc_3_day_put: z.number().optional(),
        max_perc_3_day_put: z.number().optional(),
        min_perc_30_day_total: z.number().optional(),
        max_perc_30_day_total: z.number().optional(),
        min_perc_30_day_call: z.number().optional(),
        max_perc_30_day_call: z.number().optional(),
        min_perc_30_day_put: z.number().optional(),
        max_perc_30_day_put: z.number().optional(),
        min_total_oi_change_perc: z.number().optional(),
        max_total_oi_change_perc: z.number().optional(),
        min_call_oi_change_perc: z.number().optional(),
        max_call_oi_change_perc: z.number().optional(),
        min_put_oi_change_perc: z.number().optional(),
        max_put_oi_change_perc: z.number().optional(),
        min_implied_move: z.number().optional(),
        max_implied_move: z.number().optional(),
        min_implied_move_perc: z.number().optional(),
        max_implied_move_perc: z.number().optional(),
        min_volatility: z.number().optional(),
        max_volatility: z.number().optional(),
        min_iv_rank: z.number().optional(),
        max_iv_rank: z.number().optional(),
        min_call_volume: z.number().int().nonnegative().optional(),
        max_call_volume: z.number().int().nonnegative().optional(),
        min_put_volume: z.number().int().nonnegative().optional(),
        max_put_volume: z.number().int().nonnegative().optional(),
        min_call_premium: z.number().optional(),
        max_call_premium: z.number().optional(),
        min_put_premium: z.number().optional(),
        max_put_premium: z.number().optional(),
        min_net_premium: z.number().optional(),
        max_net_premium: z.number().optional(),
        min_net_call_premium: z.number().optional(),
        max_net_call_premium: z.number().optional(),
        min_net_put_premium: z.number().optional(),
        max_net_put_premium: z.number().optional(),
        min_oi_vs_vol: z.number().optional(),
        max_oi_vs_vol: z.number().optional(),
        min_put_call_ratio: z.number().optional(),
        max_put_call_ratio: z.number().optional(),
        min_stock_volume_vs_avg30_volume: z.number().optional(),
        max_avg30_volume: z.number().optional(),
        date: z.string().optional(),
      }),
      queryRenames: { issue_types: "issue_types[]", sectors: "sectors[]" },
    },
    {
      name: "option_contracts",
      route: "/api/screener/option-contracts",
      params: z.object({
        limit: z.number().int().min(1).max(250).default(1).optional(),
        page: z.number().int().min(1).optional(),
        order: contractScreenerOrderBy.optional(),
        order_direction: z.enum(["asc", "desc"]).default("desc").optional(),
        is_otm: z.boolean().optional(),
        min_dte: z.number().int().nonnegative().optional(),
        max_dte: z.number().int().nonnegative().optional(),
        min_premium: z.number().min(0).optional(),
        max_premium: z.number().min(0).optional(),
        ticker_symbol: z.string().optional(),
        sectors: z.array(z.string()).optional(),
        min_underlying_price: z.number().optional(),
        max_underlying_price: z.number().optional(),
        exclude_ex_div_ticker: z.boolean().optional(),
        is_new: z.boolean().describe("Return only new option contracts").optional(),
        opex_only: z.boolean().describe("Return only monthly option expirations").optional(),
        unusual: z.boolean().describe("Convenience preset returning only unusual contracts").optional(),
        min_days_between_expiry_and_earnings: z.number().int().describe("Minimum days between expiry and earnings").optional(),
        max_days_between_expiry_and_earnings: z.number().int().describe("Maximum days between expiry and earnings").optional(),
        min_diff: z.number().optional(),
        max_diff: z.number().optional(),
        min_strike: z.number().optional(),
        max_strike: z.number().optional(),
        type: z.enum(["call", "Call", "put", "Put"]).optional(),
        expiry_dates: z.array(z.string()).optional(),
        min_marketcap: z.number().optional(),
        max_marketcap: z.number().optional(),
        min_volume: z.number().int().nonnegative().optional(),
        max_volume: z.number().int().nonnegative().optional(),
        min_ticker_30_d_avg_volume: z.number().optional(),
        max_ticker_30_d_avg_volume: z.number().optional(),
        min_contract_30_d_avg_volume: z.number().optional(),
        max_contract_30_d_avg_volume: z.number().optional(),
        min_multileg_volume_ratio: z.number().optional(),
        max_multileg_volume_ratio: z.number().optional(),
        min_floor_volume_ratio: z.number().optional(),
        max_floor_volume_ratio: z.number().optional(),
        min_perc_change: z.number().optional(),
        max_perc_change: z.number().optional(),
        min_daily_perc_change: z.number().optional(),
        max_daily_perc_change: z.number().optional(),
        min_avg_price: z.number().optional(),
        max_avg_price: z.number().optional(),
        min_volume_oi_ratio: z.number().optional(),
        max_volume_oi_ratio: z.number().optional(),
        min_open_interest: z.number().int().nonnegative().optional(),
        max_open_interest: z.number().int().nonnegative().optional(),
        min_floor_volume: z.number().int().nonnegative().optional(),
        max_floor_volume: z.number().int().nonnegative().optional(),
        vol_greater_oi: z.boolean().optional(),
        issue_types: z.array(z.string()).optional(),
        min_ask_perc: z.number().optional(),
        max_ask_perc: z.number().optional(),
        min_bid_perc: z.number().optional(),
        max_bid_perc: z.number().optional(),
        min_skew_perc: z.number().optional(),
        max_skew_perc: z.number().optional(),
        min_bull_perc: z.number().optional(),
        max_bull_perc: z.number().optional(),
        min_bear_perc: z.number().optional(),
        max_bear_perc: z.number().optional(),
        min_bid_side_perc_7_day: z.number().optional(),
        max_bid_side_perc_7_day: z.number().optional(),
        min_ask_side_perc_7_day: z.number().optional(),
        max_ask_side_perc_7_day: z.number().optional(),
        min_days_of_oi_increases: z.number().int().nonnegative().optional(),
        max_days_of_oi_increases: z.number().int().nonnegative().optional(),
        min_days_of_vol_greater_than_oi: z.number().int().nonnegative().optional(),
        max_days_of_vol_greater_than_oi: z.number().int().nonnegative().optional(),
        min_iv_perc: z.number().optional(),
        max_iv_perc: z.number().optional(),
        min_delta: z.number().optional(),
        max_delta: z.number().optional(),
        min_gamma: z.number().optional(),
        max_gamma: z.number().optional(),
        min_theta: z.number().optional(),
        max_theta: z.number().optional(),
        min_vega: z.number().optional(),
        max_vega: z.number().optional(),
        min_return_on_capital_perc: z.number().optional(),
        max_return_on_capital_perc: z.number().optional(),
        min_oi_change_perc: z.number().optional(),
        max_oi_change_perc: z.number().optional(),
        min_oi_change: z.number().optional(),
        max_oi_change: z.number().optional(),
        min_volume_ticker_vol_ratio: z.number().optional(),
        max_volume_ticker_vol_ratio: z.number().optional(),
        min_sweep_volume_ratio: z.number().optional(),
        max_sweep_volume_ratio: z.number().optional(),
        min_from_low_perc: z.number().optional(),
        max_from_low_perc: z.number().optional(),
        min_from_high_perc: z.number().optional(),
        max_from_high_perc: z.number().optional(),
        min_earnings_dte: z.number().int().optional(),
        max_earnings_dte: z.number().int().optional(),
        min_transactions: z.number().int().nonnegative().optional(),
        max_transactions: z.number().int().nonnegative().optional(),
        min_close: z.number().optional(),
        max_close: z.number().optional(),
        date: z.string().optional(),
      }),
      queryRenames: { sectors: "sectors[]", expiry_dates: "expiry_dates[]", issue_types: "issue_types[]" },
    },
    {
      name: "analysts",
      route: "/api/screener/analysts",
      params: z.object({
        ticker: ticker.optional(),
        limit: z.number().int().min(1).max(500).default(1).optional(),
        recommendation: z.enum(["buy", "hold", "sell"]).optional(),
        action: z.enum(["initiated", "reiterated", "downgraded", "upgraded", "maintained"]).optional(),
        newer_than: z.string().describe("Only ratings at/after this UTC timestamp (ISO-8601)").optional(),
        older_than: z.string().describe("Only ratings at/before this UTC timestamp (ISO-8601)").optional(),
      }),
    },
    {
      name: "unusual_activity",
      route: "/api/option-activity/unusual",
      params: z.object({
        ticker_symbol: z.string().describe("Comma-separated tickers. Prefix with '-' to exclude").optional(),
        sectors: z.array(z.string()).describe("Filter by underlying sector(s)").optional(),
        issue_types: z.array(z.string()).describe("Filter by issue type(s), e.g. 'Common Stock', 'ETF'").optional(),
        unusual: z.boolean().describe("Apply the unusual preset (volume>OI, OTM, DTE<=60, ask-side>=50%, premium>=$10k)").optional(),
        min_premium: z.number().int().nonnegative().describe("Minimum total premium on the contract").optional(),
        max_dte: z.number().int().describe("Maximum days to expiry").optional(),
        order: contractScreenerOrderBy.optional(),
        order_direction: z.enum(["asc", "desc"]).describe("Sort direction. Defaults to descending").optional(),
        limit: z.number().int().min(1).max(200).describe("Maximum number of results (default 100, max 200)").optional(),
        date: z.string().describe("Date in YYYY-MM-DD format").optional(),
      }),
      queryRenames: { sectors: "sectors[]", issue_types: "issue_types[]" },
    },
  ],
}
